#lint, test, and deploy on push --> run the lint, test, and deploy build scripts --> use one or three jobs
name: Deploy Workflow
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
      - name: npm install
        run: npm ci  
      - name: Lint code
        run: npm run lint
  test:      
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: install node v18
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.1'
    - name: Test code
      run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Deploy code
        run: echo "Deploying..."
  